import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import CartProvider from './components/Providers';
import ShoppingCartModal from './components/ShoppingCartModal';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='fr_ca'>
			<body className={montserrat.className}>
				<CartProvider>
					<Navbar />
					<ShoppingCartModal />
					{children}
				</CartProvider>
			</body>
		</html>
	);
}
